### ISSUE TITLE
PHPSESSID

### ISSUE THREAD

**Issue by angryahmed** [stilManiac/steamgifts-bot#6]
There is no way to find that file PHPSESSID, even on Opera, FF, IE.

**Comment by angryahmed** [comment]
Ok I found a value of PHPSESSID , but after I log out of steamgifts cookie.txt is no longer working. Every time I need to copy a new value to that file

**Comment by stilManiac** [comment]
Yes, because bot was updated and cookie is stored not in cookie.txt now. Please, see [how to run](https://github.com/stilManiac/steamgifts-bot#how-to-run) section.
