### ISSUE TITLE
Any config ?

### ISSUE THREAD

**Issue by angryahmed** [stilManiac/steamgifts-bot#7]
Why when I open program I got screen that looks not the same like on main page, even I don't get any command line, program just starting work ?

**Comment by stilManiac** [comment]
Please, be more specific. Share screen or error traceback if any.
Make sure that you're using the latest version.

**Comment by angryahmed** [comment]
Using only exe file or exe + other files make no difference. 
I got something like this - https://i.postimg.cc/sx21LMjb/as1.jpg

And program still use cookie.txt not PHPSESSID , description is wrong on your program page.

**Comment by stilManiac** [comment]
You are using old version. If you want to run the latest release, you should build bot from sources.
